// <auto-generated />
using System;
using Labb3_LudwigOleby.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Labb3_LudwigOleby.Migrations
{
    [DbContext(typeof(SampleContext))]
    partial class SampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Labb3_LudwigOleby.Models.TblBetyg", b =>
                {
                    b.Property<int>("BetygId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BetygsDatum")
                        .HasColumnType("date");

                    b.Property<string>("Kurs")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("LärarId")
                        .HasColumnType("int");

                    b.Property<string>("Slutbetyg")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasIndex("BetygId");

                    b.HasIndex("LärarId");

                    b.ToTable("tblBetyg");
                });

            modelBuilder.Entity("Labb3_LudwigOleby.Models.TblElever", b =>
                {
                    b.Property<int>("ElevId")
                        .HasColumnType("int");

                    b.Property<string>("EfterNamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FörNamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Klass")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Telefon")
                        .HasColumnType("int");

                    b.HasKey("ElevId")
                        .HasName("PK__tblEleve__4AE80D6339D69BD2");

                    b.ToTable("tblElever");
                });

            modelBuilder.Entity("Labb3_LudwigOleby.Models.TblPersonal", b =>
                {
                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.Property<string>("EfterNamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FörNamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Roll")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Telefon")
                        .HasColumnType("int");

                    b.HasKey("PersonalId")
                        .HasName("PK__tblPerso__283437F3E05594B8");

                    b.ToTable("tblPersonal");
                });

            modelBuilder.Entity("Labb3_LudwigOleby.Models.TblBetyg", b =>
                {
                    b.HasOne("Labb3_LudwigOleby.Models.TblElever", "Betyg")
                        .WithMany()
                        .HasForeignKey("BetygId")
                        .HasConstraintName("FK_tblBetyg_tblElever")
                        .IsRequired();

                    b.HasOne("Labb3_LudwigOleby.Models.TblPersonal", "Lärar")
                        .WithMany()
                        .HasForeignKey("LärarId")
                        .HasConstraintName("FK_tblBetyg_tblPersonal")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
